### ISSUE TITLE
player doesn't require items when making items

### ISSUE THREAD

**Issue by weller197** [Lusty94/lusty94_icecream#1]
I've just installed this and went to test it and the player doesn't require to have ingredients in their inventory to make the items

**Comment by Lusty94** [comment]
likely you have installed wrong or are using an usupposrted script, works fine for me and others when tested / released.

**Comment by Lusty94** [comment]
> I've just installed this and went to test it and the player doesn't require to have ingredients in their inventory to make the items

likely you have installed wrong or are using an usupported script, works fine for me and others when tested / released.

**Comment by weller197** [comment]
Would it be because I'm using a different core inventory? It has different exports for items

**Comment by Lusty94** [comment]
> Would it be because I'm using a different core inventory? It has different exports for items 

very likely mate yeah, you would need to edit the server files where items are checked for and given / taken from the player
